openapi: 3.1.1
info:
  title: Sample API
  description: Optional multiline or single-line description in [CommonMark](http://commonmark.org/help/) or HTML.
  version: 0.1.9

servers:
  - url: http://api.example.com/v1
    description: Optional server description, e.g. Main (production) server
  - url: http://staging-api.example.com
    description: Optional server description, e.g. Internal staging server for testing

paths:
  /resources:
    post:
      summary: Creates a new resource.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/resource'
      responses:
        "201":
          description: Resource created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/resource'
      tags:
        - Resources
    get:
      summary: Returns a list of resources.
      description: Optional extended description in CommonMark or HTML.
      responses:
        "200": # status code
          description: A JSON array of resources.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/resource'
      tags:
        - Resources
  '/resources/{resourceId}':
    get:
      summary: Returns a single resources.
      description: Optional extended description in CommonMark or HTML.
      parameters:
        - name: resourceId
          in: path
          description: ID of resource to fetch
          required: true
          schema:
            type: string
            format: uuid
      responses:
        "200": # status code
          description: A JSON array of resources.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/resource'
      tags:
        - Resources

components:
  schemas:
    resource:
      type: object
      properties:
        id:
          format: uuid
          type: string
          readOnly: true
        name:
          type: string
        status:
          description: Status of the resource
          enum: [BLOCKED, INSTALLING, READY]
          readOnly: true
          type: string
          example: INSTALLING
        tenantId:
          description: Tenant ID of the resource
          format: uuid
          readOnly: true
          type: string
      required:
        - id
        - name
        - status
        - tenantId

tags:
  - name: Resources
    description: Everything about your Resources
